### ISSUE TITLE
[Errno 2] No such file or directory!

### ISSUE THREAD

**Issue by lnxpy** [Mostafa-mvd/CoronaVirus#1]
Hey @Mostafa-mvd :smiley:,

I tried to run this stuff up but it didn't work properly.
The error has shown below. :point_down:
```
[Errno 2] No such file or directory:
'/home/mostafa/ProjectPy/Project/corona/coronavirus.csv'
```

I think you have to change the `file_path` to a dynamic variable. Which changes automatically on any platform. Though you need to make your own directory. I think It's gonna be better to use some sub-modules like `os.path` to create your own relative paths instead of make them defined.
Hope this trick helps you.

Thanks :heart: :)
Stay safe.

**Comment by mostafavahdanideh** [comment]
Thanks
I will do it
